### ISSUE TITLE
[nodemon] app-crashed 

### ISSUE THREAD

**Issue by AbdelfattahMohamed** [AbdelfattahMohamed/E-shopping#1]
const events = require('./routes/event-routes.js');
      ^

SyntaxError: Identifier 'events' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by AbdelfattahMohamed** [comment]
The Ans:
const events = require('./routes/event-routes.js');
app.use('/events',events);

1- make sure you restart your editor
2- cahse all files in node 
3- check the name of files , Ex: exmaple.js

**#Good_luck^^**
